import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';


const adminSource = fs.readFileSync(new URL('../js/admin.js', import.meta.url), 'utf8');
const adminHtml = fs.readFileSync(new URL('../admin.html', import.meta.url), 'utf8');
const styleSource = fs.readFileSync(new URL('../css/style.css', import.meta.url), 'utf8');


test('receipt actions offer standard and POS formats', () => {
  assert.match(adminSource, /function chooseReceiptPrintFormat\(\)/);
  assert.match(adminSource, /value="standard"[\s\S]*?Standard receipt/);
  assert.match(adminSource, /value="pos"[\s\S]*?POS receipt/);
  assert.match(adminSource, /Compact 80 mm thermal-printer layout/);
});


test('commerce and donation receipts implement an 80 mm POS document', () => {
  assert.match(adminSource, /function printOrganizationCommerceReceipt\(sale = \{\}, format = 'standard'\)/);
  assert.match(adminSource, /function printChurchDonationReceipt\(donation = \{\}, format = 'standard'\)/);
  assert.ok((adminSource.match(/@page\{size:80mm auto;margin:3mm\}/g) || []).length >= 2);
  assert.ok((adminSource.match(/Print POS receipt/g) || []).length >= 2);
  assert.match(adminSource, /Payment received with thanks<br>Generated by Dynamax/);
  assert.match(adminSource, /Thank you for your generosity<br>Verified by Dynamax/);
});


test('both receipt print buttons wait for the selected format', () => {
  assert.match(adminSource, /\[data-commerce-print\][\s\S]*?await chooseReceiptPrintFormat\(\)[\s\S]*?printOrganizationCommerceReceipt/);
  assert.match(adminSource, /\[data-print-donation\][\s\S]*?await chooseReceiptPrintFormat\(\)[\s\S]*?printChurchDonationReceipt/);
});


test('receipt chooser is compact, responsive and cache-busted', () => {
  assert.match(styleSource, /\.receipt-format-options\{[^}]*grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);
  assert.match(styleSource, /@media\(max-width:520px\)\{\.receipt-format-options\{grid-template-columns:1fr/);
  assert.match(adminHtml, /css\/style\.css\?v=20260816-attendance-name-size/);
});
